# This file has been generated by mavenix 0.2.0. Configure the build here!
{
  system ? builtins.currentSystem,
  pkgs ? import <nixpkgs> { inherit system; },
  mavenix ? import (fetchTarball {
    url = "https://github.com/icetan/mavenix/archive/v0.2.0.tar.gz";
    sha256 = "18s6v7q8s9nd3wym2agiyc7cpbkd3jfb0hli99jiy649wnxkmf3j";
  }) { inherit pkgs; },
  maven ? pkgs.maven.override { jdk = pkgs.jdk11; },

  src ? pkgs.fetchFromGitHub {
    owner = "georgewfraser";
    repo = "vscode-javac";
    rev = "52145590facdc609dc8c39babcff741044e7848e";
    sha256 = "08h4yrrryarxrsljcrjxm47qzl7aw3lgk1ga32fpih56mlkd4lq1";
  },
  doCheck ? false,
}: mavenix.buildMaven {
  inherit maven src doCheck;
  infoFile = ./mavenix.lock;

  buildInputs = with pkgs; [ makeWrapper ];

  MAVEN_OPTS = "-Dfile.encoding=UTF-8";

  configurePhase = "true"; # Skip ./configure
  installPhase = ''
    mkdir -p $out/{bin,share/java}
    cp -v out/fat-jar.jar $out/share/java/

    makeWrapper ${maven.jdk}/bin/java $out/bin/javacs \
      --add-flags "-jar $out/share/java/fat-jar.jar" \
      --add-flags "-Xverify:none" \
      --set JAVA_HOME "${maven.jdk}/jre" \
      --prefix PATH : ${maven}/bin
  '';

  meta = with pkgs.stdenv.lib; {
    homepage = https://github.com/georgewfraser/vscode-javac;
    description = "Java Compiler API Language Server";
    license = licenses.mit;
    maintainers = with maintainers; [ ];
    platforms = [ "x86_64-linux" ];
  };
}
