# This file has been generated by mavenix 0.2.0. Configure the build here!

let
  mavenix-src = fetchTarball { url = "https://github.com/icetan/mavenix/archive/v1.0.0.tar.gz"; sha256 = "1lz5f77clvk0fj4qh2352w6n1vcxz55v2d4sw0mb3q4wdmw0aqf1"; };
in {
  pkgs ? (import mavenix-src {}).pkgs,
  mavenix ? import mavenix-src { inherit pkgs; },
  maven ? pkgs.maven.override { jdk = pkgs.jdk11; },

  src ? fetchGit {
    url = git://github.com/georgewfraser/vscode-javac;
    rev = "52145590facdc609dc8c39babcff741044e7848e";
  },
  doCheck ? false,
}: mavenix.buildMaven {
  inherit maven src doCheck;
  infoFile = ./mavenix.lock;
  #infoFile = mavenix.updateInfo (oldAttrs: {
  #  remotes = oldAttrs.remotes // { hej = "https://repository.jboss.org/nexus/content/groups/public"; };
  #});

  buildInputs = with pkgs; [ makeWrapper ];

  MAVEN_OPTS = "-Dfile.encoding=UTF-8";

  configurePhase = "true"; # Skip ./configure
  installPhase = ''
    mkdir -p $out/{bin,share/java}
    cp -v out/fat-jar.jar $out/share/java/

    makeWrapper ${maven.jdk}/bin/java $out/bin/javacs \
      --add-flags "-jar $out/share/java/fat-jar.jar" \
      --add-flags "-Xverify:none" \
      --set JAVA_HOME "${maven.jdk}/jre" \
      --prefix PATH : ${maven}/bin
  '';

  meta = with pkgs.stdenv.lib; {
    homepage = https://github.com/georgewfraser/vscode-javac;
    description = "Java Compiler API Language Server";
    license = licenses.mit;
    maintainers = with maintainers; [ ];
    platforms = [ "x86_64-linux" ];
  };
}
